### ISSUE TITLE
Failure of qirxacc_XaccQuantumTest

### ISSUE THREAD

**Issue by wongey** [ORNL-QCI/qiree#10]
This is because XACC's minimal build for QIREE does not include `qsim`.

Recommend temporary deactivation until XACC's full functionality is employed. Or, alternatively, ask @danclaudino to add qsim to the minimal build and we can keep this test.

**Comment by sethrj** [comment]
@wongey could we switch the test to use `aer`?

**Comment by wongey** [comment]
Good idea. See: [PR #11](https://github.com/ORNL-QCI/qiree/pull/11)
