### ISSUE TITLE
Teleport

### ISSUE THREAD

**Issue by wongey** [ORNL-QCI/qiree#3]
It should be noted that [at this point](https://github.com/ORNL-QCI/qiree/commit/c321f8ebb392d453d069627541d0745f3f9f94d3), `qiree` runs teleport correctly with llvm-16 and [eclipse-xacc](https://github.com/eclipse/xacc) using BOTH the `aer` simulator and `honeywell:H1-1E`, which validates that XACC (via staq) can work with Honeywell on the teleport experiment.

However, the [current version](https://github.com/wongey/qir-xir/tree/624d15304ae5f08b37366a433dc9e3fd2b64fa41) of the `qiree` does NOT run teleport correctly, but the team plans to resolve this issue with some transpilation techniques.

TODOs (transferred from private repo):
- Translate if statements without else to xacc: visit each block and check that else are empty and check which measurement is the conditional for.
- Check ifstmt translation to vendors (yes it does!).
- Verify teleport results from "successful" trial (yes!).
- New QIS/RT implementation for writing out pytkt code for execution on Honeywell?

**Comment by sethrj** [comment]
First step is preprocessing the QIR using the LLVM IR functions:
- Eliminate empty [blocks](https://llvm.org/doxygen/classllvm_1_1BasicBlock.html)
- Verify that the only terminators are [`br`](https://llvm.org/docs/LangRef.html#br-instruction) and [`ret`](https://llvm.org/docs/LangRef.html#ret-instruction)
- Verify that the condition for each `br` is the output of the last `__quantum__qis__read_result__body` call
- Verify that the "true" branch has an unconditional `br`
- Verify that that the "false" branch is the same as the destination of that `br`
- Inject `begin_if` at the end of the conditional block, and `end_if` instructions at the end of the "true" block

Next step:
- Add begin_if/end_if runtime functions to the quantum interface
- Add an `xacc::ir::asComposite(provider->createInstruction("ifstmt" ... `  to `XaccQuantum`
- Activate the "if" statement during the scope of the block

**Comment by sethrj** [comment]
Performing LLVM transformation passes looks like a no-go without some serious digging or help from Anthony...

**Comment by wongey** [comment]
A resolution to this issue can be found at PR #17 in the form of a qsim app implementation to QIR-EE. It removes the need to rely on XACC to handle mid-circuit measurements. The conversation can be continued there.
